/**
 * The Operation type system — pure data describing what should happen
 * during algorithm execution (PROJECT.md sections 6 and 18).
 *
 * This module intentionally contains no functions, no Execution Engine
 * logic, no algorithm logic, and no React/UI code. It only defines the
 * shape of the Operation types the MVP currently supports, so it stays
 * independent of every other layer.
 *
 * Fields are `readonly` to reflect that, once generated by the Algorithm,
 * an Operation is treated as immutable (PROJECT.md 18.7).
 */

/** The pair of array indices an Operation acts on. */
export type OperationIndices = readonly [number, number]

/**
 * Represents a comparison between two array positions.
 *
 * Does not modify the array, and does not store the values being
 * compared or the comparison result (PROJECT.md 18.4) — the Visualizer
 * uses only the indices to highlight the compared elements.
 */
export interface CompareOperation {
  readonly type: 'compare'
  readonly indices: OperationIndices
}

/**
 * Represents exchanging the values at two array positions.
 *
 * Reversible by performing the same swap again, so no previous values
 * need to be stored (PROJECT.md 18.5).
 */
export interface SwapOperation {
  readonly type: 'swap'
  readonly indices: OperationIndices
}

/**
 * The MVP currently supports exactly these two Operation types.
 * Do not add MARK, INSERT, REMOVE, MOVE, VISIT, or any other variant
 * without an explicit PROJECT.md decision (see section 18.3).
 */
export type Operation = CompareOperation | SwapOperation
